spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: aylla
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  properties:
    hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace





